# Generated by Django 4.2.1 on 2023-05-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d', verbose_name='Добавить изображение'),
        ),
    ]
